# Generated by Django 4.1.3 on 2022-11-12 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_patient'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patient',
            old_name='adress',
            new_name='p_adress',
        ),
    ]
