# Generated by Django 4.1.3 on 2022-11-12 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_patientr_delete_patient'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patientr',
            old_name='p_adress',
            new_name='addrss',
        ),
    ]
