# Generated by Django 4.1.3 on 2022-11-13 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_patientr_id'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PatientR',
            new_name='Patient',
        ),
    ]
