# Generated by Django 4.1.3 on 2022-11-17 16:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_rename_patientr_patient'),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientR',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('dob', models.CharField(max_length=100)),
                ('gender', models.CharField(max_length=20)),
                ('marital', models.CharField(max_length=20)),
                ('lga', models.CharField(max_length=100)),
                ('addrss', models.TextField(blank=True)),
                ('state', models.CharField(max_length=100)),
                ('apparatus', models.CharField(max_length=100)),
                ('room', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=1000)),
                ('create_at', models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
        migrations.DeleteModel(
            name='Patient',
        ),
    ]
